<?php

namespace PatrykMolenda\NetPolicy\Render\Cisco;

use PatrykMolenda\NetPolicy\Domain\Action;
use PatrykMolenda\NetPolicy\Domain\PolicySet;
use PatrykMolenda\NetPolicy\Exception\RenderException;
use PatrykMolenda\NetPolicy\Render\RenderContext;
use PatrykMolenda\NetPolicy\Render\RendererInterface;

final class IosXrRenderer implements RendererInterface
{
    /**
     * Render PolicySet to Cisco IOS-XR configuration
     *
     * @param PolicySet $set
     * @param RenderContext $context
     * @return string
     * @throws RenderException
     */
    public function render(PolicySet $set, RenderContext $context): string
    {
        $output = [];
        $output[] = "! Generated by NetPolicy";
        $output[] = "! " . date('Y-m-d H:i:s');
        $output[] = "!";

        // Render prefix-sets first
        $prefixSets = $this->renderPrefixSets($set);
        if (!empty($prefixSets)) {
            $output = array_merge($output, $prefixSets);
            $output[] = "!";
        }

        // Render route-policies
        foreach ($set->sorted()->policies() as $policy) {
            $output = array_merge($output, $this->renderPolicy($policy));
            $output[] = "!";
        }

        $output[] = "end";

        return implode("\n", $output);
    }

    /**
     * Render prefix-sets from all rules
     *
     * @param PolicySet $set
     * @return array
     */
    protected function renderPrefixSets(PolicySet $set): array
    {
        $output = [];
        $prefixes = [];

        // Collect all unique prefixes
        foreach ($set->policies() as $policy) {
            foreach ($policy->rules() as $rule) {
                $prefix = $rule->match()->prefix();
                if ($prefix !== null) {
                    $cidr = $prefix->cidr();
                    if (!in_array($cidr, $prefixes)) {
                        $prefixes[] = $cidr;
                    }
                }
            }
        }

        // Render prefix-set if we have prefixes
        if (!empty($prefixes)) {
            $output[] = "prefix-set NETPOLICY-PREFIXES";
            foreach ($prefixes as $prefix) {
                $output[] = "  $prefix";
            }
            $output[] = "end-set";
        }

        return $output;
    }

    /**
     * Render a single policy as route-policy
     *
     * @param \PatrykMolenda\NetPolicy\Domain\Policy $policy
     * @return array
     */
    protected function renderPolicy(\PatrykMolenda\NetPolicy\Domain\Policy $policy): array
    {
        $output = [];
        $output[] = "route-policy {$policy->name()}";

        foreach ($policy->rules() as $ruleIndex => $rule) {
            $match = $rule->match();
            $action = $rule->action();

            // Build if statement
            $conditions = [];

            if ($match->prefix() !== null) {
                $conditions[] = "destination in NETPOLICY-PREFIXES";
            }

            if ($match->asn() !== null) {
                $conditions[] = "as-path neighbor-is " . $match->asn()->value();
            }

            if (!empty($conditions)) {
                $output[] = "  if " . implode(" and ", $conditions) . " then";
            } else {
                $output[] = "  if true then";
            }

            // Render action
            switch ($action->type()) {
                case Action::ACCEPT:
                    // Set attributes if any
                    $attrs = $action->attributes()->all();
                    if (isset($attrs['local-pref'])) {
                        $output[] = "    set local-preference " . $attrs['local-pref'];
                    }
                    if (isset($attrs['community'])) {
                        $output[] = "    set community (" . $attrs['community'] . ")";
                    }
                    if (isset($attrs['med'])) {
                        $output[] = "    set med " . $attrs['med'];
                    }
                    $output[] = "    pass";
                    break;

                case Action::REJECT:
                    $output[] = "    drop";
                    break;

                case Action::MODIFY:
                    $attrs = $action->attributes()->all();
                    if (isset($attrs['local-pref'])) {
                        $output[] = "    set local-preference " . $attrs['local-pref'];
                    }
                    if (isset($attrs['community'])) {
                        $output[] = "    set community (" . $attrs['community'] . ")";
                    }
                    if (isset($attrs['med'])) {
                        $output[] = "    set med " . $attrs['med'];
                    }
                    $output[] = "    pass";
                    break;
            }

            $output[] = "  endif";
        }

        // Default action
        $output[] = "  drop";
        $output[] = "end-policy";

        return $output;
    }
}